# Generated by Django 3.1 on 2020-08-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goods')),
                ('info_img', models.ImageField(upload_to='infoImage')),
                ('title', models.CharField(max_length=30)),
                ('short_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('goods_each', models.CharField(max_length=24, null=True)),
                ('each_weight', models.CharField(max_length=24, null=True)),
                ('transfer', models.CharField(max_length=24, null=True)),
                ('packing', models.CharField(max_length=64, null=True)),
                ('origin', models.CharField(max_length=48, null=True)),
                ('allergy', models.CharField(max_length=126, null=True)),
                ('info', models.CharField(max_length=126, null=True)),
                ('limit', models.CharField(max_length=64, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.category')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.type')),
            ],
        ),
    ]
