# Generated by Django 3.1 on 2020-08-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goods')),
                ('title', models.CharField(max_length=30)),
                ('short_desc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('goods_each', models.CharField(max_length=24, null=True)),
                ('each_weight', models.CharField(max_length=24, null=True)),
                ('transfer', models.CharField(max_length=24, null=True)),
                ('packing', models.CharField(max_length=64, null=True)),
                ('origin', models.CharField(max_length=48, null=True)),
                ('allergy', models.CharField(max_length=126, null=True)),
                ('info', models.CharField(max_length=126, null=True)),
                ('limit', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
