# Generated by Django 3.1 on 2020-08-24 08:58

from django.db import migrations, models
import django.db.models.deletion
import goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=goods.models.goods_img_path, verbose_name='메인이미지')),
                ('info_img', models.ImageField(upload_to=goods.models.goods_info_img_path, verbose_name='상품 이미지')),
                ('title', models.CharField(max_length=60, verbose_name='상품 명')),
                ('short_desc', models.CharField(max_length=100, verbose_name='간단 설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('each', models.CharField(max_length=64, null=True, verbose_name='판매 단위')),
                ('weight', models.CharField(max_length=64, null=True, verbose_name='중량/용량')),
                ('transfer', models.CharField(max_length=64, null=True, verbose_name='배송 구분')),
                ('packing', models.CharField(max_length=128, null=True, verbose_name='포장 타입')),
                ('origin', models.CharField(max_length=48, null=True, verbose_name='원산지')),
                ('allergy', models.CharField(max_length=512, null=True, verbose_name='알레르기 정보')),
                ('info', models.CharField(max_length=512, null=True, verbose_name='제품 정보')),
                ('expiration', models.CharField(max_length=512, null=True, verbose_name='유통기한')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.category')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', related_query_name='types', to='goods.goods')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', related_query_name='types', to='goods.type')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsExplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=goods.models.goods_img_1_path, verbose_name='상품 설명 이미지')),
                ('text_title', models.CharField(max_length=64)),
                ('text_context', models.CharField(max_length=128, verbose_name='상품 문맥')),
                ('text_description', models.CharField(max_length=512, verbose_name='설명')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explains', to='goods.goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=128)),
                ('detail_desc', models.CharField(max_length=512)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='goods.goods')),
            ],
        ),
    ]
