# Generated by Django 3.1 on 2020-08-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200822_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', related_query_name='types', to='goods.goods'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', related_query_name='types', to='goods.type'),
        ),
    ]
